import { PageConfig } from './page-config.model';

export class TabConfig {
  /**
   * Configuration of the page to be shown in the tab.
   */
  page: PageConfig = new PageConfig();

  /**
   * Current ID of the tab with the page.
   * Generated by Chrome.
   */
  tabId: number = 0;

  /**
   * Indicates if the page is successfully loaded.
   */
  tabIdReady: boolean = false;

  /**
   * ID of the tab refreshed version of the page that will be shown next.
   * Generated by Chrome.
   */
  nextTabId: number = 0;

  /**
   * Indicates if the refreshed version of the page is successfully loaded.
   */
  nextTabIdReady: boolean = false;

  /**
   * Indicates if the tab is active (current).
   */
  active: boolean = false;

  /**
   * Number of the current retry to load the page.
   */
  retryCount: number = 0;

  /**
   * Timer to reload the page.
   */
  reloadTimer?: number | ReturnType<typeof setInterval>;

  constructor(init?: Partial<TabConfig>) {
    Object.assign(this, init);
  }
}
