import { PageConfig } from './page-config.model';

export class TabConfig {
  /**
   * Configuration of the page to be shown in the tab.
   */
  page: PageConfig = new PageConfig();
  /**
   * ID of the tab generated by Chrome.
   */
  tabId: number = 0;

  /**
   * Indicates if the tab is active (current).
   */
  active: boolean = false;

  /**
   * When set to true, the tab will not be shown.
   * Happens when the page is not loaded correctly.
   */
  skip: boolean = false;

  /**
   * Number of the current retry to load the page.
   */
  retryCount: number = 0;

  /**
   * Timer to reload the page.
   */
  reloadTimer?: number | ReturnType<typeof setInterval>;

  constructor(init?: Partial<TabConfig>) {
    Object.assign(this, init);
  }
}
